"""Backend capability registry for Ouroboros runtimes and providers."""

from ouroboros.backends.capabilities import (
    BackendCapability,
    RuntimeSubagentOrchestrationContract,
    SkillExecutionCapability,
    SubagentDispatchMode,
    SubagentSpawnTriggerMechanism,
    ToolDiscoveryMechanism,
    backend_supports_tool_envelope,
    build_runtime_subagent_orchestration_contract,
    get_backend_capability,
    interview_driver_backend_choices,
    llm_backend_choices,
    render_backend_skill_capability_guide,
    render_mcp_server_instructions,
    resolve_backend_alias,
    resolve_interview_driver_backend,
    resolve_llm_backend_name,
    resolve_runtime_backend_name,
    resolve_subagent_dispatch,
    resolve_tool_discovery,
    runtime_backend_choices,
    soft_tool_enforcement_backends,
)
from ouroboros.backends.factory_registry import (
    BackendFactorySpec,
    backend_factory_specs,
    get_backend_factory_spec,
)

__all__ = [
    "BackendCapability",
    "BackendFactorySpec",
    "RuntimeSubagentOrchestrationContract",
    "SkillExecutionCapability",
    "SubagentDispatchMode",
    "SubagentSpawnTriggerMechanism",
    "ToolDiscoveryMechanism",
    "backend_supports_tool_envelope",
    "backend_factory_specs",
    "build_runtime_subagent_orchestration_contract",
    "get_backend_capability",
    "get_backend_factory_spec",
    "interview_driver_backend_choices",
    "llm_backend_choices",
    "resolve_backend_alias",
    "render_backend_skill_capability_guide",
    "render_mcp_server_instructions",
    "resolve_interview_driver_backend",
    "resolve_llm_backend_name",
    "resolve_runtime_backend_name",
    "resolve_subagent_dispatch",
    "resolve_tool_discovery",
    "runtime_backend_choices",
    "soft_tool_enforcement_backends",
]
